# Takes data from the "calls" table in the MongoDB and output logging statistics

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv('calls_test_dump.zip') # Exported from mongodb "calls" table
print("Data from:\n",df['timestamp'].iloc[0],"\n",df['timestamp'].iloc[-1])
# How many different room_ids are there?
print("Number of different room_ids:",len(df['room_id'].unique())) 
print("Number of different user_ids:",len(df['client_id'].unique()))

df

Data from:
 2022-12-15 15:15:59.439689
 2022-12-18 14:22:22.881353
Number of different room_ids: 2384
Number of different user_ids: 4756

,_id,client_id,client_type,client_username,iplocation,logging_type,room_id,state,test_id,timestamp,latest_circuit,error
0,639b3a2f5aca3f51110bfaed,09783a84-13e1-4ae1-8270-b159811a4ec0,None,c1-Normal,"{""wanIp"": ""130.225.170.33"", ""country"": ""Denmar...",CLIENT_END,2bc81288-30db-4e44-89a9-c4744f004454,call_ended,1b26f938-27fd-4b3b-8902-2731ee6d62d1,2022-12-15 15:15:59.439689,NaN,NaN
1,639b3a2f9322090472d7dae7,aebe7c01-72f3-403e-9839-969e9a3f50bf,None,d1-Normal,"{""wanIp"": ""130.225.170.34"", ""country"": ""Denmar...",CLIENT_END,2bc81288-30db-4e44-89a9-c4744f004454,call_ended,1b26f938-27fd-4b3b-8902-2731ee6d62d1,2022-12-15 15:15:59.571617,NaN,NaN
2,639b3a66f791a84ad0119dc9,NaN,CnC,NaN,NaN,COMMAND_START_RUN,NaN,NaN,6c7c6ab4-8709-47dc-b639-d3398ffc14a6,2022-12-15 15:16:54.029077,NaN,NaN
3,639b3a66f791a84ad0119dcb,NaN,CnC,NaN,NaN,COMMAND_START_TEST,dbf91666-ca22-4cae-88d3-efc63b9b2c83,NaN,6c7c6ab4-8709-47dc-b639-d3398ffc14a6,2022-12-15 15:16:54.077615,NaN,NaN
4,639b3a6b762322f970119dcd,NaN,CnC,d1-Normal,NaN,COMMAND_SESSION_START,dbf91666-ca22-4cae-88d3-efc63b9b2c83,NaN,6c7c6ab4-8709-47dc-b639-d3398ffc14a6,2022-12-15 15:16:59.672625,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
26309,639f220daea15179dca031db,NaN,CnC,d1-Normal,NaN,COMMAND_SESSION_START,d862db86-d0c6-4aee-a250-13992a83670c,NaN,a99eac52-0524-438f-a011-8cd69cb87f94,2022-12-18 14:22:05.916551,NaN,NaN
26310,639f221866df18908b0f34e5,0e573990-8f14-4834-9a19-c62aae0b65cc,None,d1-Normal,NaN,CLIENT_START,d862db86-d0c6-4aee-a250-13992a83670c,starting_session,a99eac52-0524-438f-a011-8cd69cb87f94,2022-12-18 14:22:16.626289,NaN,NaN
26311,639f221ba0061832aec88502,9ba0e482-66ca-4006-aaa9-0f8e43017b03,None,c1-Normal,NaN,CLIENT_START,d862db86-d0c6-4aee-a250-13992a83670c,starting_session,a99eac52-0524-438f-a011-8cd69cb87f94,2022-12-18 14:22:19.699785,NaN,NaN
26312,639f221ca0061832aec88503,9ba0e482-66ca-4006-aaa9-0f8e43017b03,None,c1-Normal,NaN,CLIENT_RUNNING,d862db86-d0c6-4aee-a250-13992a83670c,call_in_progress,a99eac52-0524-438f-a011-8cd69cb87f94,2022-12-18 14:22:20.833835,NaN,NaN
26313,639f221e66df18908b0f34e6,0e573990-8f14-4834-9a19-c62aae0b65cc,None,d1-Normal,NaN,CLIENT_RUNNING,d862db86-d0c6-4aee-a250-13992a83670c,call_in_progress,a99eac52-0524-438f-a011-8cd69cb87f94,2022-12-18 14:22:22.881353,NaN,NaN

## Look at how many calls there are in the database and how they are classified

In [5]:
df_tmp = df
roomId = "adc7e3dd-a813-4d42-8c40-d3cf78ae79e5"

# drop rows where roomId is not 1234567890
df_tmp_room = df_tmp[df_tmp.room_id == roomId]
df_tmp_room

,_id,client_id,client_type,client_username,iplocation,logging_type,room_id,state,test_id,timestamp,latest_circuit,error
26207,639f1e6991380542a0a031c5,NaN,CnC,NaN,NaN,COMMAND_START_TEST,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,NaN,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:06:33.559202,NaN,NaN
26208,639f1e729c8953fc00a031c7,NaN,CnC,c6-Lokinet,NaN,COMMAND_SESSION_START,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,NaN,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:06:42.336940,NaN,NaN
26209,639f1e7257743c0303a031c7,NaN,CnC,d6-Lokinet,NaN,COMMAND_SESSION_START,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,NaN,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:06:42.339688,NaN,NaN
26210,639f1e85ab8250560e2bbbf5,a14c195b-7ffe-4d57-ad38-d7651ac9c700,Lokinet:Proxy,c6-Lokinet,NaN,CLIENT_START,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,starting_session,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:07:01.424888,NaN,NaN
26211,639f1e87469efa34c6e87135,6064c098-10b2-4206-9103-614d1d92a285,Lokinet:Proxy,d6-Lokinet,NaN,CLIENT_START,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,starting_session,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:07:03.603335,NaN,NaN
26212,639f1e8dab8250560e2bbbf6,a14c195b-7ffe-4d57-ad38-d7651ac9c700,Lokinet:Proxy,c6-Lokinet,NaN,CLIENT_RUNNING,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,call_in_progress,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:07:09.664575,NaN,NaN
26213,639f1e8d469efa34c6e87136,6064c098-10b2-4206-9103-614d1d92a285,Lokinet:Proxy,d6-Lokinet,NaN,CLIENT_RUNNING,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,call_in_progress,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:07:09.853465,NaN,NaN
26214,639f1ecc469efa34c6e87137,6064c098-10b2-4206-9103-614d1d92a285,Lokinet:Proxy,d6-Lokinet,"{""wanIp"": ""93.95.230.88"", ""country"": ""Iceland""...",CLIENT_END,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,call_ended,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:08:12.780831,NaN,NaN
26215,639f1ecdab8250560e2bbbf7,a14c195b-7ffe-4d57-ad38-d7651ac9c700,Lokinet:Proxy,c6-Lokinet,"{""wanIp"": ""93.95.230.88"", ""country"": ""Iceland""...",CLIENT_END,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,call_ended,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:08:13.039985,NaN,NaN
26216,639f1ed357743c0303a031c9,NaN,CnC,d6-Lokinet,NaN,COMMAND_SESSION_SUCCESS,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,NaN,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:08:19.059811,NaN,NaN
26217,639f1ed39c8953fc00a031c9,NaN,CnC,c6-Lokinet,NaN,COMMAND_SESSION_SUCCESS,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,NaN,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:08:19.374919,NaN,NaN

In [19]:
# Find the different logging_types that the client c6 is associated with or has sent
df_tmp = df
client_username = "c6-Lokinet"

# drop rows where client_username is not X
df_tmp_room = df_tmp[df_tmp.client_username == client_username]
# Count how many times logging_type is CLIENT_ERROR
logging_type_stat = df_tmp_room.groupby('logging_type')["client_username"].count()
logging_type_stat

logging_type
CLIENT_END                 174
CLIENT_ERROR                 9
CLIENT_RUNNING             182
CLIENT_START               183
COMMAND_SESSION_FAILED       9
COMMAND_SESSION_START      183
COMMAND_SESSION_SUCCESS    174
Name: client_username, dtype: int64

In [7]:
# Find out how many unique client_usernames there are
df_tmp = df
df_tmp = df_tmp.drop_duplicates(subset=['client_username'])['client_username']
# Drop NaN values
df_tmp = df_tmp.dropna()
client_usernames = list(df_tmp)
print(client_usernames,"Number of client usernames:",len(client_usernames))
# ['c1-Normal', 'd1-Normal', 'c2-TorNormal', 'd2-TorNormal', 'd3-TorEurope', 'c3-TorEurope', 'c4-TorScandinavia', 'd4-TorScandinavia', 'd6-Lokinet', 'c6-Lokinet'] Number of client usernames: 10

['c1-Normal', 'd1-Normal', 'c2-TorNormal', 'd2-TorNormal', 'd3-TorEurope', 'c3-TorEurope', 'c4-TorScandinavia', 'd4-TorScandinavia', 'd6-Lokinet', 'c6-Lokinet'] Number of client usernames: 10

In [8]:
# Go through each client_username and count how many times logging_types are sent
logging_type_stat = []
for client_username in client_usernames[:3]:
    df_tmp = df
    # drop rows where client_username is not X
    df_tmp_room = df_tmp[df_tmp.client_username == client_username]
    # Count how many times logging_type is CLIENT_ERROR
    logging_type_stat.append(df_tmp_room.groupby('logging_type')["client_username"].count())
    print(client_username,logging_type_stat[-1]) # [-1] is the last element in the list (len(list)-1)
#logging_type_stat

c1-Normal logging_type
CLIENT_END                  988
CLIENT_ERROR                111
CLIENT_RUNNING             1090
CLIENT_START               1099
COMMAND_SESSION_FAILED      112
COMMAND_SESSION_START      1100
COMMAND_SESSION_SUCCESS     987
Name: client_username, dtype: int64
d1-Normal logging_type
CLIENT_END                 185
CLIENT_RUNNING             185
CLIENT_START               185
COMMAND_SESSION_START      185
COMMAND_SESSION_SUCCESS    184
Name: client_username, dtype: int64
c2-TorNormal logging_type
CLIENT_END                 451
CLIENT_ERROR                99
CLIENT_RUNNING             543
CLIENT_START               549
COMMAND_SESSION_FAILED      99
COMMAND_SESSION_START      550
COMMAND_SESSION_SUCCESS    450
Name: client_username, dtype: int64

In [9]:
logging_type_stat = []
for client_username in client_usernames[3:6]:
    df_tmp = df
    # drop rows where client_username is not X
    df_tmp_room = df_tmp[df_tmp.client_username == client_username]
    # Count how many times logging_type is CLIENT_ERROR
    logging_type_stat.append(df_tmp_room.groupby('logging_type')["client_username"].count())
    print(client_username,logging_type_stat[-1]) # [-1] is the last element in the list (len(list)-1)
#logging_type_stat

d2-TorNormal logging_type
CLIENT_END                 508
CLIENT_ERROR                42
CLIENT_RUNNING             540
CLIENT_START               549
COMMAND_SESSION_FAILED      42
COMMAND_SESSION_START      550
COMMAND_SESSION_SUCCESS    507
Name: client_username, dtype: int64
d3-TorEurope logging_type
CLIENT_END                 518
CLIENT_ERROR                31
CLIENT_RUNNING             545
CLIENT_START               549
COMMAND_SESSION_FAILED      31
COMMAND_SESSION_START      549
COMMAND_SESSION_SUCCESS    518
Name: client_username, dtype: int64
c3-TorEurope logging_type
CLIENT_END                 296
CLIENT_ERROR                69
CLIENT_RUNNING             363
CLIENT_START               365
COMMAND_SESSION_FAILED      70
COMMAND_SESSION_START      366
COMMAND_SESSION_SUCCESS    296
Name: client_username, dtype: int64

In [10]:
logging_type_stat = []
for client_username in client_usernames[6:9]:
    df_tmp = df
    # drop rows where client_username is not X
    df_tmp_room = df_tmp[df_tmp.client_username == client_username]
    # Count how many times logging_type is CLIENT_ERROR
    logging_type_stat.append(df_tmp_room.groupby('logging_type')["client_username"].count())
    print(client_username,logging_type_stat[-1]) # [-1] is the last element in the list (len(list)-1)
#logging_type_stat

c4-TorScandinavia logging_type
CLIENT_END                  82
CLIENT_ERROR               101
CLIENT_RUNNING             174
CLIENT_START               183
COMMAND_SESSION_FAILED     101
COMMAND_SESSION_START      183
COMMAND_SESSION_SUCCESS     82
Name: client_username, dtype: int64
d4-TorScandinavia logging_type
CLIENT_END                 426
CLIENT_ERROR               304
CLIENT_RUNNING             719
CLIENT_START               730
COMMAND_SESSION_FAILED     306
COMMAND_SESSION_START      732
COMMAND_SESSION_SUCCESS    426
Name: client_username, dtype: int64
d6-Lokinet logging_type
CLIENT_END                 350
CLIENT_ERROR                16
CLIENT_RUNNING             364
CLIENT_START               366
COMMAND_SESSION_FAILED      16
COMMAND_SESSION_START      366
COMMAND_SESSION_SUCCESS    350
Name: client_username, dtype: int64

In [11]:
logging_type_stat = []
for client_username in client_usernames[9:]:
    df_tmp = df
    # drop rows where client_username is not X
    df_tmp_room = df_tmp[df_tmp.client_username == client_username]
    # Count how many times logging_type is CLIENT_ERROR
    logging_type_stat.append(df_tmp_room.groupby('logging_type')["client_username"].count())
    print(client_username,logging_type_stat[-1]) # [-1] is the last element in the list (len(list)-1)
#logging_type_stat

c6-Lokinet logging_type
CLIENT_END                 174
CLIENT_ERROR                 9
CLIENT_RUNNING             182
CLIENT_START               183
COMMAND_SESSION_FAILED       9
COMMAND_SESSION_START      183
COMMAND_SESSION_SUCCESS    174
Name: client_username, dtype: int64

### Get an overview of errors

In [12]:
# Which client_username has the most CLIENT_ERROR compared to other logging_types?
logging_type_stat = []
for client_username in client_usernames:
    df_tmp = df
    # drop rows where client_username is not X
    df_tmp_room = df_tmp[df_tmp.client_username == client_username]
    # Count how many times logging_type is CLIENT_ERROR
    loggin_types = df_tmp_room.groupby('logging_type')["client_username"].count()
    amount_of_sessions = loggin_types["CLIENT_START"]
    if "CLIENT_ERROR" in loggin_types:
        logging_type_stat.append(loggin_types['CLIENT_ERROR'])
    else:
        logging_type_stat.append(0)

    print(client_username,"Sessions:",amount_of_sessions,"Errors: ",logging_type_stat[-1], "Percentage failed: ","{:.2f}%".format(100*(logging_type_stat[-1]/amount_of_sessions))) # [-1] is the last element in the list (len(list)-1)

c1-Normal Sessions: 1099 Errors:  111 Percentage failed:  10.10%
d1-Normal Sessions: 185 Errors:  0 Percentage failed:  0.00%
c2-TorNormal Sessions: 549 Errors:  99 Percentage failed:  18.03%
d2-TorNormal Sessions: 549 Errors:  42 Percentage failed:  7.65%
d3-TorEurope Sessions: 549 Errors:  31 Percentage failed:  5.65%
c3-TorEurope Sessions: 365 Errors:  69 Percentage failed:  18.90%
c4-TorScandinavia Sessions: 183 Errors:  101 Percentage failed:  55.19%
d4-TorScandinavia Sessions: 730 Errors:  304 Percentage failed:  41.64%
d6-Lokinet Sessions: 366 Errors:  16 Percentage failed:  4.37%
c6-Lokinet Sessions: 183 Errors:  9 Percentage failed:  4.92%

## What circuits did c4-TorScandinavia use?

In [13]:
import json
df_tmp = df
client_username = "c4-TorScandinavia"

# drop rows where client_username is not X
df_tmp = df_tmp[df_tmp.client_username == client_username]
c4_circuits = df_tmp["latest_circuit"].dropna()
c4_circuits_unique = c4_circuits.drop_duplicates()

print("Number of circuits:",len(c4_circuits))
print("Number of unique circuits:",len(c4_circuits_unique))

# drop nan values from df_tmp["latest_circuit"]
df_tmp = df_tmp.dropna(subset=['latest_circuit'])

# parse the latest_circuit column to a list
circuits = df_tmp["latest_circuit"].tolist()
# parse the list of json strings to a list of dictionaries
circuits = [json.loads(circuit) for circuit in circuits]

# go through each circuit and create a new list with the circuit_id
circuit_list = []
for circuit in circuits:
    for c in circuit["Circuits"]:
        circuit_list.append(circuit["Circuits"][c])


circuit_list_df = pd.DataFrame({"A":circuit_list})
print("list len:",len(circuit_list_df))
circuit_list_df.drop_duplicates(inplace=True)
print("list len (dup removed):",len(circuit_list_df))
circuit_list_df

Number of circuits: 68
Number of unique circuits: 68
list len: 105
list len (dup removed): 95

                                                     A
0    {'Entry Node': {'Fingerprint': '1A81BEE054FE5C...
1    {'Entry Node': {'Fingerprint': 'AE5BFD2CFA3FEF...
2    {'Entry Node': {'Fingerprint': 'AE5BFD2CFA3FEF...
3    {'Entry Node': {'Fingerprint': '1A81BEE054FE5C...
4    {'Entry Node': {'Fingerprint': 'AE5BFD2CFA3FEF...
..                                                 ...
100  {'Entry Node': {'Fingerprint': 'AE5BFD2CFA3FEF...
101  {'Entry Node': {'Fingerprint': 'AE5BFD2CFA3FEF...
102  {'Entry Node': {'Fingerprint': '1A81BEE054FE5C...
103  {'Entry Node': {'Fingerprint': 'AE5BFD2CFA3FEF...
104  {'Entry Node': {'Fingerprint': 'AE5BFD2CFA3FEF...

[95 rows x 1 columns]

In [17]:
# Count how many times each country is used as entry, middle and exit node
# TODO: This is first interesting to see, when the clients also send the circuits
# that was used in a failing session.
# See https://github.com/Master2022E/OnionRTC-experiment/issues/29#issuecomment-1356852164

#print("Len of circuit_list:",len(circuit_list))
print("Count how many times each country is used as entry, middle and exit node")
dk_counter = 0
se_counter = 0
no_counter = 0
fi_counter = 0

for circuit in circuit_list:
    entry= circuit["Entry Node"]["Country"].upper()
    middle = circuit["Middle Node"]["Country"].upper()
    exit = circuit["Exit node"]["Country"].upper()
    node_countries = [entry,middle,exit]

    for country in node_countries:
        if country == "DK":
            dk_counter += 1
        if country == "SE":
            se_counter += 1
        if country == "NO":
            no_counter += 1
        if country == "FI":
            fi_counter += 1

print("DK:",dk_counter)
print("SE:",se_counter)
print("NO:",no_counter)
print("FI:",fi_counter)

Count how many times each country is used as entry, middle and exit node
DK: 72
SE: 116
NO: 20
FI: 107

In [15]:
# latest_circuit is only collected for clients that send CLIENT_END
df_tmp = df
client_username = "c4-TorScandinavia"

# drop rows where client_username is not X
df_tmp = df_tmp[df_tmp.client_username == client_username]
df_tmp.dropna(subset = ['latest_circuit'], inplace=True)
df_tmp
loggin_types = df_tmp.groupby('logging_type')["client_username"].count()
loggin_types

/tmp/ipykernel_45302/2984120512.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tmp.dropna(subset = ['latest_circuit'], inplace=True)

logging_type
CLIENT_END    68
Name: client_username, dtype: int64

# Look at the calls from the same room

In [16]:
df_tmp = df
roomId = "adc7e3dd-a813-4d42-8c40-d3cf78ae79e5"

# drop rows where roomId is not 1234567890
df_tmp_room = df_tmp[df_tmp.room_id == roomId]
df_tmp_room

,_id,client_id,client_type,client_username,iplocation,logging_type,room_id,state,test_id,timestamp,latest_circuit,error
26207,639f1e6991380542a0a031c5,NaN,CnC,NaN,NaN,COMMAND_START_TEST,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,NaN,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:06:33.559202,NaN,NaN
26208,639f1e729c8953fc00a031c7,NaN,CnC,c6-Lokinet,NaN,COMMAND_SESSION_START,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,NaN,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:06:42.336940,NaN,NaN
26209,639f1e7257743c0303a031c7,NaN,CnC,d6-Lokinet,NaN,COMMAND_SESSION_START,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,NaN,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:06:42.339688,NaN,NaN
26210,639f1e85ab8250560e2bbbf5,a14c195b-7ffe-4d57-ad38-d7651ac9c700,Lokinet:Proxy,c6-Lokinet,NaN,CLIENT_START,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,starting_session,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:07:01.424888,NaN,NaN
26211,639f1e87469efa34c6e87135,6064c098-10b2-4206-9103-614d1d92a285,Lokinet:Proxy,d6-Lokinet,NaN,CLIENT_START,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,starting_session,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:07:03.603335,NaN,NaN
26212,639f1e8dab8250560e2bbbf6,a14c195b-7ffe-4d57-ad38-d7651ac9c700,Lokinet:Proxy,c6-Lokinet,NaN,CLIENT_RUNNING,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,call_in_progress,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:07:09.664575,NaN,NaN
26213,639f1e8d469efa34c6e87136,6064c098-10b2-4206-9103-614d1d92a285,Lokinet:Proxy,d6-Lokinet,NaN,CLIENT_RUNNING,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,call_in_progress,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:07:09.853465,NaN,NaN
26214,639f1ecc469efa34c6e87137,6064c098-10b2-4206-9103-614d1d92a285,Lokinet:Proxy,d6-Lokinet,"{""wanIp"": ""93.95.230.88"", ""country"": ""Iceland""...",CLIENT_END,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,call_ended,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:08:12.780831,NaN,NaN
26215,639f1ecdab8250560e2bbbf7,a14c195b-7ffe-4d57-ad38-d7651ac9c700,Lokinet:Proxy,c6-Lokinet,"{""wanIp"": ""93.95.230.88"", ""country"": ""Iceland""...",CLIENT_END,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,call_ended,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:08:13.039985,NaN,NaN
26216,639f1ed357743c0303a031c9,NaN,CnC,d6-Lokinet,NaN,COMMAND_SESSION_SUCCESS,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,NaN,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:08:19.059811,NaN,NaN
26217,639f1ed39c8953fc00a031c9,NaN,CnC,c6-Lokinet,NaN,COMMAND_SESSION_SUCCESS,adc7e3dd-a813-4d42-8c40-d3cf78ae79e5,NaN,c91b6dbd-ab9d-4163-9c58-cd94c21dd995,2022-12-18 14:08:19.374919,NaN,NaN